### ISSUE TITLE
URI::tcp namespace permissions

### ISSUE THREAD

**Issue by Grinnz** [avast/URI-tcp#1]
FYI, SOAP::Lite is currently inadvertently holding permissions on the URI::tcp namespace: https://rt.cpan.org/Public/Bug/Display.html?id=118554

You may need to contact the authors by email to ask them to release or transfer the permissions in PAUSE (only the firstcome KULCHENKO can do this, or pause admins), please also CC modules@perl.org.

**Comment by JaSei** [comment]
Hi, thanks for your information... I will try contact authors by email...

**Comment by JaSei** [comment]
https://github.com/redhotpenguin/soaplite/pull/31

**Comment by JaSei** [comment]
Problem solved...
`URI::tcp` are not indexed as `SOAP::Lite` now
and my `URI::tcp` are released

thank you a lot for your tips @Grinnz
